name: DemoNewCD
on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: echo Hello, Test World!
  

dev:
  runs-on: ubuntu-latest
  environment:
    name: dev
    url: 'https://www.youtube.com/'
  needs: build
  steps:
    - name: Run a one-line script
      run: echo Deplos Dev
      
hmg:
  runs-on: ubuntu-latest
  environment:
    name: hmg
    url: 'https://www.google.com/'
  needs: deploy-dev
  steps:
    - name: Run a one-line script
      run: echo Deplos HMG    
      
prd:
  runs-on: ubuntu-latest
  environment:
    name: prd
    url: 'https://www.twitter.com/'
  needs: deploy-hmg
  steps:
    - name: Run a one-line script
      run: echo Deplos PRD      
